import { ArrowLeft, ArrowRight, Check, CircleDot, Cloud, Code2, Database, ExternalLink, FileSpreadsheet, FolderOpen, Image, KeyRound, LockKeyhole, MessageCircle, Rocket, Server, ShieldCheck, ShoppingBag, Upload } from "lucide-react";
import type { ReactNode } from "react";

const Code = ({ children }: { children: ReactNode }) => <code className="setup-code">{children}</code>;

export default function SetupGuide() {
  return <main className="setup-page">
    <header className="setup-header"><a href="/" className="setup-brand">TREVO<span>Launch guide</span></a><nav><a href="/admin">Admin dashboard</a><a href="/"><ArrowLeft /> Webstore</a></nav></header>
    <section className="setup-hero"><div><p className="eyebrow">No-code launch checklist</p><h1>Your Trevo store is built.<br /><em>Here&apos;s how to make it live.</em></h1><p>Complete the steps below in order. The webstore works in demo mode now; real orders, payments and automatic WhatsApp messages activate as you add your own service credentials.</p><div className="setup-progress"><span><Check /> Storefront built</span><span><Check /> Admin built</span><span><CircleDot /> Connect services</span><span><CircleDot /> Publish</span></div></div></section>

    <div className="setup-body">
      <aside className="setup-nav"><p>On this page</p><a href="#stack">Recommended stack</a><a href="#architecture">Architecture</a><a href="#firebase">1. Firebase</a><a href="#catalog">2. Products & images</a><a href="#whatsapp">3. WhatsApp</a><a href="#payments">4. Payments</a><a href="#local">5. Run locally</a><a href="#deploy">6. Deploy</a><a href="#security">Security</a><a href="#roadmap">MVP & phase 2</a></aside>
      <article className="setup-content">
        <section className="setup-section intro" id="stack"><span className="section-number">Stack</span><h2>Recommended technology</h2><p>This project uses a modern web stack that is fast, maintainable and suitable for a growing fashion brand.</p><div className="stack-grid"><article><Code2 /><h3>Web app</h3><p>Next.js-style Vinext, React 19 and TypeScript for the storefront and admin dashboard.</p></article><article><Database /><h3>Data</h3><p>Firebase Firestore, Authentication and Storage. Sites D1/R2 adapters are also included for immediate hosted persistence.</p></article><article><Server /><h3>Backend</h3><p>Validated server APIs plus Firebase Cloud Functions for orders, payments, inventory and webhooks.</p></article><article><Cloud /><h3>Hosting</h3><p>OpenAI Sites for the working build; Firebase Hosting, Cloudflare or Netlify remain compatible alternatives.</p></article></div></section>

        <section className="setup-section" id="architecture"><span className="section-number">Overview</span><h2>How everything connects</h2><div className="architecture-flow"><div><ShoppingBag /><b>Customer store</b><small>Catalog · cart · checkout</small></div><ArrowRight /><div><Server /><b>Secure APIs</b><small>Validation · order totals</small></div><ArrowRight /><div><Database /><b>Firebase / D1</b><small>Products · orders · users</small></div><div className="flow-branches"><span><MessageCircle /> WhatsApp Cloud API</span><span><KeyRound /> Payment provider</span><span><Image /> Storage</span></div></div><p>Customers browse products in the webstore. The server validates every order and recalculates totals before saving it. The admin reads the same order record, updates fulfilment and payment status, and can contact the customer through WhatsApp.</p></section>

        <section className="setup-section" id="firebase"><span className="section-number">Step 1</span><h2>Connect Firebase</h2><p className="lead">Estimated time: 15–20 minutes. You only do this once.</p><ol className="setup-steps"><li><div>1</div><span><b>Create the project</b><p>Open <a href="https://console.firebase.google.com/" target="_blank" rel="noreferrer">Firebase Console <ExternalLink /></a>, choose <strong>Add project</strong>, name it <strong>Trevo Store</strong>, and follow the prompts.</p></span></li><li><div>2</div><span><b>Turn on three services</b><p>Open <strong>Build</strong> in the left menu. Create a Firestore Database in production mode, enable Email/Password and Google under Authentication, and enable Storage.</p></span></li><li><div>3</div><span><b>Add a web app</b><p>Open Project settings → Your apps → Web. Register <strong>Trevo Web</strong>. Firebase shows six configuration values. Copy each value into a new file named <Code>.env.local</Code>, following <Code>.env.example</Code>.</p></span></li><li><div>4</div><span><b>Add server credentials</b><p>Project settings → Service accounts → Generate new private key. Keep the downloaded JSON private. Set <Code>GOOGLE_APPLICATION_CREDENTIALS</Code> to its full file path before importing products.</p></span></li><li><div>5</div><span><b>Deploy security rules</b><p>Install Firebase CLI and sign in, then run:</p><Code>npm install -g firebase-tools<br />firebase login<br />firebase use --add<br />firebase deploy --only firestore:rules,storage</Code></span></li></ol><div className="setup-warning"><LockKeyhole /><span><b>Never upload the service-account JSON or .env.local to GitHub.</b><p>The included .gitignore protects the usual secret files. Firebase browser keys are identifiable but security still depends on Auth, App Check and rules.</p></span></div></section>

        <section className="setup-section" id="catalog"><span className="section-number">Step 2</span><h2>Upload products and images</h2><div className="two-methods"><article><FileSpreadsheet /><h3>Your Trevo CSV is included</h3><p>The live catalog is built from <Code>data/TREVO_Firebase_Products.csv</Code>. Its supported headings are SKU, Product Name, Category, Regular Price, Sale Price, Stock and Image URL. Future CSV files can use the same format.</p><Code>npm run firebase:import:check -- --file "data/TREVO_Firebase_Products.csv"<br />npm run firebase:import -- --file "data/TREVO_Firebase_Products.csv"</Code><small>The first command checks all rows without changing Firebase.</small></article><article><FolderOpen /><h3>Images from folders</h3><p>Create one folder per SKU inside <Code>data/product-images</Code>. Example: <Code>data/product-images/TRV-PC-001/</Code>. Name photos 01.jpg, 02.jpg, 03.jpg in display order.</p><Code>npm run firebase:upload-images -- --folder "data/product-images"</Code><small>The script uploads images and connects their URLs to matching SKUs.</small></article></div><div className="setup-tip"><Upload /><span><b>Admin method</b><p>After Firebase Admin authentication is active, use Admin dashboard → Products → Import CSV or Add product. Product photos accept JPG, PNG or WebP up to 8 MB.</p></span></div></section>

        <section className="setup-section" id="whatsapp"><span className="section-number">Step 3</span><h2>Configure WhatsApp</h2><p>The store already supports reliable <Code>wa.me</Code> checkout using <strong>+92 300 7041451</strong>. This opens the customer&apos;s WhatsApp with cart items and totals pre-filled—no API approval is required.</p><div className="option-table"><div><b>MVP — already active</b><p>WhatsApp checkout and support deep links. You respond manually from WhatsApp Business.</p><span>Cost: Free</span></div><div><b>Automated confirmations</b><p>Create a Meta Business app, add WhatsApp Cloud API, then fill <Code>WHATSAPP_PHONE_NUMBER_ID</Code>, <Code>WHATSAPP_ACCESS_TOKEN</Code> and <Code>WHATSAPP_VERIFY_TOKEN</Code>. Point the Meta webhook to the deployed <Code>whatsappWebhook</Code> function.</p><span>Requires Meta approval and message templates</span></div></div><p>Automatic order confirmation and tracking messages must use Meta-approved templates outside the 24-hour customer-service window.</p></section>

        <section className="setup-section" id="payments"><span className="section-number">Step 4</span><h2>Configure payment collection</h2><p>The live MVP supports the payment rules already requested:</p><ul className="check-list"><li><Check /> JazzCash: 0300 7041451</li><li><Check /> EasyPaisa: 0300 7041451</li><li><Check /> Bank transfer instructions are provided through Trevo WhatsApp</li><li><Check /> Cash on delivery — Rs. 200 security advance before dispatch</li><li><Check /> Standard delivery — free above Rs. 1,500, otherwise Rs. 250</li><li><Check /> Urgent delivery — Rs. 500 and never free</li></ul><p>The payment number is already included in checkout. For online cards or wallets later, open an approved merchant account with your chosen provider, set <Code>PAYMENT_PROVIDER</Code>, add its public/secret keys, and register its signed webhook URL. The backend&apos;s <Code>paymentWebhook</Code> updates the matching order only after verifying the webhook secret.</p><div className="setup-warning soft"><ShieldCheck /><span><b>Trevo never stores card numbers.</b><p>Customers enter card details only in the payment provider&apos;s hosted or tokenized payment screen. Store references and payment status, not raw card data.</p></span></div></section>

        <section className="setup-section" id="local"><span className="section-number">Step 5</span><h2>Run the website on your computer</h2><ol className="setup-steps compact"><li><div>1</div><span><b>Install Node.js 22</b><p>Download the LTS installer from nodejs.org.</p></span></li><li><div>2</div><span><b>Open the project folder in Terminal</b><Code>cd trevo-fashion-store</Code></span></li><li><div>3</div><span><b>Install and start</b><Code>npm install<br />npm run dev</Code><p>Open the local address printed in Terminal. Stop it with Ctrl+C.</p></span></li></ol><p>Storefront: <Code>/</Code> · Admin: <Code>/admin</Code> · This guide: <Code>/setup</Code></p></section>

        <section className="setup-section" id="deploy"><span className="section-number">Step 6</span><h2>Deploy from GitHub and connect trevopk.com</h2><p>GitHub stores the source code but does not run this store&apos;s secure backend. Do not use GitHub Pages. The simplest setup is GitHub + Vercel for the web app, with Firebase handling products, orders, authentication and storage.</p><ol className="setup-steps compact"><li><div>1</div><span><b>Create a separate GitHub repository</b><p>Name it <strong>trevo-webstore</strong> and keep it private while testing. Upload the complete project contents—not the outer ZIP folder. Do not upload <Code>node_modules</Code>, <Code>.env.local</Code> or Firebase service-account JSON.</p></span></li><li><div>2</div><span><b>Deploy Firebase resources</b><Code>firebase deploy --only functions,firestore:rules,storage</Code></span></li><li><div>3</div><span><b>Import your attached products</b><Code>npm run firebase:import -- --file "data/TREVO_Firebase_Products.csv"</Code></span></li><li><div>4</div><span><b>Connect GitHub to Vercel</b><p>In Vercel choose Add New → Project → Import <strong>trevo-webstore</strong>. Framework: Next.js. Build command: <Code>npm run build:vercel</Code>. Add the values from <Code>.env.example</Code> as Environment Variables, then deploy.</p></span></li><li><div>5</div><span><b>Connect the domain</b><p>Add <strong>trevopk.com</strong> and <strong>www.trevopk.com</strong> in Vercel. Copy the exact DNS records Vercel displays into GoDaddy. Remove old Netlify records only after the new Vercel address is fully tested.</p></span></li><li><div>6</div><span><b>Test one real order</b><p>Confirm it appears in Admin, receives the correct delivery fee, uses WhatsApp 0300 7041451 and changes payment status only after verification.</p></span></li></ol></section>

        <section className="setup-section" id="security"><span className="section-number">Required</span><h2>Security and compliance checklist</h2><ul className="security-grid"><li><LockKeyhole /><span><b>Admin access</b>Enable Firebase Auth and grant the custom <Code>admin: true</Code> claim only to the owner account.</span></li><li><ShieldCheck /><span><b>Order validation</b>The server recalculates subtotal, delivery and total. Never trust totals sent by the browser.</span></li><li><KeyRound /><span><b>Secrets</b>Keep service accounts, provider secrets and webhook secrets in hosted environment variables.</span></li><li><Database /><span><b>Customer privacy</b>Collect only delivery information, publish a privacy policy, and delete data according to your retention policy.</span></li><li><Image /><span><b>Uploads</b>Restrict file type and size. Product images are public; payment proofs must remain admin-only.</span></li><li><Server /><span><b>Operations</b>Enable Firebase App Check, alerts, backups and error monitoring before paid advertising.</span></li></ul></section>

        <section className="setup-section" id="roadmap"><span className="section-number">Plan</span><h2>Implementation priority</h2><div className="roadmap"><article><span>MVP · included</span><h3>Start selling reliably</h3><ul><li>Responsive catalog, product galleries and filters</li><li>Cart, wishlist and guest checkout</li><li>WhatsApp checkout and support</li><li>Delivery and advance-payment rules</li><li>Admin products, orders, customers and payments</li><li>CSV import, Firebase schema and image upload</li><li>Inventory alerts and basic sales reporting</li></ul></article><article><span>Phase 2</span><h3>Automate and scale</h3><ul><li>Fully synced customer accounts and wishlists</li><li>Automated WhatsApp templates and tracking events</li><li>Live card/wallet gateway and automatic refunds</li><li>Courier API and printed shipping labels</li><li>Discount codes, abandoned carts and email flows</li><li>Pixel analytics, attribution and conversion reporting</li><li>Multi-vendor roles and vendor payout ledger if Trevo opens to sellers</li></ul></article></div></section>

        <section className="launch-card"><Rocket /><div><p className="eyebrow">Ready for your data</p><h2>Next: add your Trevo CSV and real bag photos.</h2><p>The code is complete. Product data and third-party credentials are the only remaining inputs.</p></div><a href="/admin">Open admin dashboard <ArrowRight /></a></section>
      </article>
    </div>
  </main>;
}
